### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by kebodev** [KPLauritzen/worldcup2018#4]
Hi, im running your code:

python3 luigitasks.py DoPredictions --local-scheduler

And got this:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/luigi/worker.py", line 203, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.6/site-packages/luigi/worker.py", line 140, in _run_get_new_deps
    task_gen = self.task.run()
  File "/Users/kulig/Foci/worldcup2018/src/league.py", line 218, in run
    concat_df = pd.concat(collected_dfs, sort=True, axis=0)
TypeError: concat() got an unexpected keyword argument 'sort'

**Comment by kebodev** [comment]
sorry it was due to pandas..
